<main id="main">
    <section id="mens-issue" class="mens-issue">
        <div class="container">
            <div class="section-title mt-5 pt-5">
                <h2>Privacy Practices</h2>
            </div>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>THIS NOTICE DESCRIBES HOW MEDICAL INFORMATION ABOUT YOU MAY BE USED AND DISCLOSED AND HOW YOU CAN GET ACCESS TO THIS INFORMATION. IF ITS NOT TOO MUCH TROUBLE, REVIEW IT CAREFULLY.</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp;</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>This Notice of Privacy Practices (the &quot;Notice&quot;) portrays how Doctor Matrix Medical Group, P.A. (&quot;we&quot; or &quot;our&quot;) may utilize and uncover your safeguarded wellbeing data to do treatment, instalment or business tasks and for different purposes that are allowed or legally necessary. We are not a &quot;Covered Entity&quot; as that term is characterized in the Health Insurance Portability and Accountability Act (&quot;HIPAA&quot;), yet we have chosen to intentionally significantly conform to the guidelines set out in HIPAA. &quot;Safeguarded wellbeing data&quot; or &quot;PHI&quot; is data about you, including segment data, that might distinguish you and that connects with your past, present or future actual wellbeing or condition, treatment or instalment for medical care administrations. This Notice additionally portrays your privileges to access and control your safeguarded wellbeing data.</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp;</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>Utilizations AND DISCLOSURES OF PROTECTED HEALTH INFORMATION:</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp;</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>Your safeguarded wellbeing data might be utilized and unveiled by our medical care suppliers, our staff, and others beyond our office that are engaged with your consideration and therapy to give medical services administrations to you, to help our business tasks, to get instalment for your consideration, and some other utilize approved or legally necessary.</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp;</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>TREATMENT:</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp;</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>We will utilize and unveil your safeguarded wellbeing data to give, coordinate, or deal with your medical care and any connected administrations. This incorporates the coordination or the executives of your medical services with an outsider. For instance, your safeguarded wellbeing data might be given to a medical services supplier to whom you have been alluded to guarantee the vital data is open to analyse or treat you.</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp;</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>Instalment:</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp;</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>Your safeguarded wellbeing data might be utilized to charge or get instalment for your medical care administrations. This might incorporate specific exercises that your health care coverage plan might attempt before it supports or pays for your administrations, for example, making an assurance of qualification or inclusion for protection benefits and checking on administrations gave to you to clinical need.</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp;</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>Medical services OPERATIONS:</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp;</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>We might utilize or unveil, depending on the situation, your safeguarded wellbeing data to help the business exercises of this office. These exercises incorporate, yet are not restricted to, working on nature of care, giving data about treatment choices or other wellbeing related advantages and administrations, improvement or keeping up with and supporting PC frameworks, legitimate administrations, and directing reviews and consistence programs, including misrepresentation, waste and misuse examinations.</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp;</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>Utilizations AND DISCLOSURES THAT DO NOT REQUIRE YOUR AUTHORIZATION</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp;</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>We might involve or uncover your safeguarded wellbeing data in the accompanying circumstances without your approval. These circumstances incorporate the accompanying purposes and exposures: as legally necessary; for general wellbeing purposes; for medical care oversight purposes; for misuse or disregard announcing; according to Food and Drug Administration necessities; regarding official procedures; for policing; to coroners, memorial service chiefs and organ gift organizations; for specific examination purposes; for specific crimes; for specific military action and public safety purposes; for labourers&rsquo; pay revealing; connecting with specific detainee detailing; and other required uses and divulgences. Under the law, we should make specific divulgences to you upon your solicitation, and when expected by the Secretary of the Department of Health and Human Services to research or decide our consistence with the necessities of the Health Insurance Portability and Accountability Act (HIPAA). State regulations might additionally confine these divulgences.</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp;</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>Utilizations AND DISCLOSURES THAT REQUIRE YOUR AUTHORIZATION:</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp;</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>Other allowed and required utilizations and divulgences will be made uniquely with your assent, approval or potential chance to protest except if allowed or legally necessary. Without your approval, we are explicitly disallowed from involving or revealing your safeguarded wellbeing data for promoting. We may not sell your safeguarded wellbeing data without your approval. Your safeguarded wellbeing data won&apos;t utilize for raise support. Assuming you give us an approval for specific purposes and exposures of your data, you might renounce such approval, whenever, recorded as a hard copy, but to the degree that we have made a move in dependence on the utilization or revelation showed in the approval.</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp;</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>YOUR RIGHTS WITH RESPECT TO YOUR PROTECTED HEALTH INFORMATION:</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp;</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>You reserve the privilege to examine and duplicate your safeguarded wellbeing data.</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp;</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>You might demand admittance to or a change of your safeguarded wellbeing data.</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp;</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>You reserve the option to demand a limitation on the utilization or divulgence of your safeguarded wellbeing/individual data. Your solicitation should be recorded as a hard copy and express the particular limitation mentioned and to whom you believe the limitation should apply. We are not expected to consent to a limitation that you might ask for, with the exception of assuming the mentioned limitation is on a divulgence to a wellbeing plan for an instalment or medical care activities reason in regards to a help that has been settled completely from cash on hand.</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp;</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>You reserve the option to demand to get private interchanges from us by elective means or at a substitute area. We will consent to all sensible solicitations submitted recorded as a hard copy which determine how or where you wish to get these interchanges.</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp;</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>You reserve the option to demand a correction of your projected wellbeing data. On the off chance that we deny your solicitation for alteration, you reserve the option to record an assertion of conflict with us. We might set up an answer to our assertion and we will furnish you with a duplicate of any such rejoinder.</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp;</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>You reserve the privilege to get a bookkeeping of specific divulgences of your safeguarded wellbeing data that we have made, paper or electronic, aside from specific revelations which were according to an approval, for motivations behind treatment, instalment, medical services activities (except if the data is kept up with in an electronic wellbeing record); or for specific different purposes.</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp;</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>You reserve the privilege to get a paper duplicate of this Notice, upon demand, regardless of whether you have recently mentioned its receipt electronically by email.</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp;</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>Amendments TO THIS NOTICE:</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp;</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>We maintain whatever authority is needed to re-examine this Notice and to make the modified Notice powerful for safeguarded wellbeing data we as of now have about you as well as any data we get from now on. You are qualified for a duplicate of the Notice presently active. Any huge changes to this Notice will be posted on our site. You then, at that point, reserve the privilege to protest or pull out as given in this Notice.</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp;</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>Break OF HEALTH INFORMATION:</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp;</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>We will advise you assuming that a reportable break of your unstable safeguarded wellbeing data is found. Warning will be made to you no later than 60 days from the break disclosure and will incorporate a concise portrayal of how the break happened, the safeguarded wellbeing data included and contact data for you to clarify some pressing issues.</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp;</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>Protests:</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp;</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>Protests about this Notice or how we handle your safeguarded wellbeing data ought to be coordinated to our HIPAA Privacy Officer. In the event that you are not happy with how a protest is taken care of you might present a conventional grievance to the Department of Health and Human Services, Office for Civil Rights by sending a letter to 200 Independence Avenue, S.W., Washington, D.C. 20201 or visiting www.hhs.gov/ocr/security/hipaa/objections/. We won&apos;t fight back against you for documenting an objection.</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp;</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>We should follow the obligations and protection rehearses depicted in this Notice. We will keep up with the security of your safeguarded wellbeing data and to tell impacted people following a break of unstable safeguarded wellbeing data. Assuming you have any inquiries regarding this Notice, if it&apos;s not too much trouble, reach us at <a href="mailto:support@ed-ayurveda.com">support@ed-ayurveda.com</a> and request to talk with our HIPAA Privacy Officer.</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp;</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:center;'><strong><u>Your proceeded with utilization of our Site comprises your concurrence with this of Notice of Privacy Practices.</u></strong></p>
        </div>
    </section>
</main>