<main id="main">
    <section id="mens-issue" class="mens-issue">
        <div class="container">
            <div class="section-title mt-5 pt-5">
                <h2>ED-Ayurveda Agreement for Self-Payment of Services</h2>
            </div>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>Specialist Matrix Medical Group is focused on giving the best quality medical services administrations. We take an interest in no protection plans, including Medicare or Medicaid, and we acknowledge no health care coverage at all. Our administrations are 100% self-pay by our patients. By marking this structure, that&apos;s what you recognize: 1) you have no health care coverage through a PPO, HMO, Medicaid or Medicare or some other protection plan; or 2) you have health care coverage however you would rather not utilize any protection benefit for these administrations, recognizing that Doctor Matrix Medical Group acknowledges no health care coverage.</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp;</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>Your insurance strategy is a policy among you and your insurance agency. It is your obligation to know your advantages, and how they will apply to your advantage instalments, and we assume no liability to comprehend or be limited by the agreements of such protection. By marking this structure, you are choosing for buy benefits that could possibly be covered by your protection assuming you got those administrations from an alternate supplier. You have chosen administrations for buy from us on a self-pay premise. As such, you have guided us to treat your acquisition of these administrations as though you are a uninsured patient and you consent to be 100% answerable for full instalment of the recorded cost of the administrations. There is no assurance your insurance agency will make any instalment on the expense of the administrations you have bought.</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp;</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>Specialist Matrix Medical Group has given you the charges, ahead of time, for the administrations you have mentioned. Your proceeded with utilization of our Site establishes your understanding; you consent to cover these charges as a self-pay patient, choosing not for utilize an insurance contract benefit. You have been given a decision of various administrations, alongside their expenses. You have chosen the administrations and will acknowledge full monetary obligation regarding instalment.</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp;</p>
            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;'>I have perused the Agreement for Self-Payment of Services. I get it and consent to this Agreement.</p>
        </div>
    </section>
</main>